module.exports = () => [
  'You shut your mouth, you have all the strengths.',
  'You know my code: hoes before bros. Uteruses before duderuses…Ovaries before brovaries.',
  "I'm going to be direct and honest with you. I would like a glass of red wine and I'll take the cheapest one you have because I can't tell the difference.",
  'Relationships are like SCUBA diving. If you come up too fast you get the bends. And the reasons why I know this is because I was dating a guy once and we were SCUBA diving and I told him that I loved him underwater and he shot up really fast and got the bends.',
  'We need to remember what’s important in life: friends, waffles, work. Or waffles, friends, work. Doesn’t matter, but work is third.',
  'I’m a feminist, okay? I would never ever go to a strip club. I’ve gone on record that if I had to have a stripper’s name, it would be Equality.',
  'You should ask her on horseback. No, you should ask her in a hot air balloon. No, she should be on a hot air balloon and you should ride up on horseback. Oh, wait. She’s in the balloon; you ride up on horseback. You point to the sky. Up there, skywriting. Marry me, Ann.',
  'I am big enough to admit that I am often inspired by myself.',
  "I'm cried out but I want to cry more so I'm rehydrating.",
  'Oh Ann, you beautiful rule-breaking moth.',
  'Ann, you beautiful spinster, I will find you love.',
  'Ann, you beautiful tropical fish.',
  'Ann, you poetic and noble land-mermaid.',
  "I'm gonna get drunk and then I'm gonna order a three course meal where each course is made of dessert.",
  'If you look inside your bags you will find a few things. A bouquet of hand crocheted flower pens, a mosaic portrait of each of you made from the crushed bottles of your favorite diet soda and a personalized 5,000-word essay of why you are all so awesome.',
  "The library is the worst group of people ever assembled in history. They're mean, conniving, rude, and extremely well-read, which makes them dangerous.",
  'I stand behind my decision to avoid salad and other disgusting things.',
  'I mean, that’s why people respect Hillary Clinton so much, because nobody takes a punch like her. She’s the strongest, smartest punching bag in the world.',
  'Why would anyone ever eat anything besides breakfast food?',
  'One person’s ‘annoying’ is another person’s ‘inspiring and heroic’.',
  "I ate a brownie once. At a party in college. It was intense. It was kind of indescribable, actually. I felt like I was floating. Turns out there wasn't any pot in the brownie. It was just an insanely good brownie.",
  'Sophisticated with a hint of slutty.',
  'Calzones are pointless. They’re just pizza that’s harder to eat. No one likes them.',
  'Slowing down is not really my jam.',
  "Winning is every girl's dream.",
  'Some people object to powerful depictions of awesome ladies.',
  'What I hear when I’m being yelled at is people caring loudly at me.',
  'Ann, beautiful, talented, brilliant, powerful musk ox.',
  'Guys love it when you can show them you’re better than they are at something they love.',
  'I’m a goddess, a glorious female warrior.',
  'Good, I hate paperwork. I hardly ever do it in my bed on a Saturday night listening to old Spice Girls CDs.',
  'Ain’t no party like a Leslie Knope party, ‘cause a Leslie Knope party is 30 parties.',
  'Tom Haverford is a selfish, sleazy, self-promoting, good-hearted, secretly kind and wonderful tiny, little person.',
  'Oh! You know what’s always sexy? Fingerless gloves.',
  'I need you to text me every 30 seconds saying that everything is gonna be okay.',
  'We’re all just calm and happy people together enjoying ourselves on earth.',
  'Look, am I proud of it? Yes, because Eagleton sucks. Is it the classiest move? Yes, because Eagleton sucks. Would I do it again? Yes, because Eagleton sucks.',
  'I took your idea and I made it better.',
  'No one achieves anything alone.',
  'Math is worthless in real life.',
  'I am super chill all the time.',
  "Hey, Leslie. It's Leslie. Hang in there. I love you. Bye.",
  "If I seem too passionate, it's because I care. If I come off too strong, it's because I feel strongly. And if I push too hard, it's because things aren't moving fast enough.",
  "I'm ready.",
  'There’s nothing we can’t do if we work hard, never sleep, and shirk all other responsibilities in our lives.',
  "No matter what I do, literally nothing bad can happen to me. I'm like a white male US senator.",
  'I would like to be president some day, so, no, I have not smoked marijuana.'
];
